apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: castle-db
  namespace: escape-the-castle
  labels:
    app: escape-the-castle
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
